# Generated by Django 2.2.16 on 2020-09-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interactio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100)),
                ('output', models.TextField()),
                ('script', models.TextField()),
                ('execute_script', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'interaction',
            },
        ),
    ]
