# Generated by Django 2.2.16 on 2020-09-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interactio',
            new_name='Interaction',
        ),
    ]
