# Generated by Django 2.2.16 on 2020-09-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200906_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='hasButton',
            field=models.BooleanField(default=False),
        ),
    ]
