# Generated by Django 2.2.16 on 2020-09-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200906_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='buttons',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='script',
            field=models.TextField(),
        ),
    ]
