# Generated by Django 2.2.16 on 2020-09-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200906_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='buttons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='hasButton',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
